config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :album_reviews

      resources :song_reviews

      resources :genres

      resources :artists

      resources :albums

      resources :songs

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "songs#index"
  resources :album_reviews
  resources :song_reviews
  resources :genres
  resources :artists
  resources :albums
  resources :songs
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Direct associations

  has_many   :songs,
             dependent: :destroy

  has_many   :albums,
             dependent: :destroy

  # Indirect associations

  has_many   :album_reviews,
             through: :albums,
             source: :album_reviews

  # Validations

  # Scopes

  def to_s
    artist_image
  end
end

app/controllers/api/v1/artists_controller.rb
class Api::V1::ArtistsController < Api::V1::GraphitiController
  def index
    artists = ArtistResource.all(params)
    respond_with(artists)
  end

  def show
    artist = ArtistResource.find(params)
    respond_with(artist)
  end

  def create
    artist = ArtistResource.build(params)

    if artist.save
      render jsonapi: artist, status: :created
    else
      render jsonapi_errors: artist
    end
  end

  def update
    artist = ArtistResource.find(params)

    if artist.update_attributes
      render jsonapi: artist
    else
      render jsonapi_errors: artist
    end
  end

  def destroy
    artist = ArtistResource.find(params)

    if artist.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: artist
    end
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[show edit update destroy]

  def index
    @q = Artist.ransack(params[:q])
    @artists = @q.result(distinct: true).includes(:albums, :songs,
                                                  :album_reviews).page(params[:page]).per(10)
  end

  def show
    @song = Song.new
    @album = Album.new
  end

  def new
    @artist = Artist.new
  end

  def edit; end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist, notice: "Artist was successfully created."
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist, notice: "Artist was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_url, notice: "Artist was successfully destroyed."
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:artist_image, :artist_bio)
  end
end

app/views/artists/_artist_album_reviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Album Reviews
  </div>

  <ul class="list-group list-group-flush">
    <% @artist.album_reviews.each do |album_review| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/album_reviews/<%= album_review.id %>">
          <%= album_review %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/artists/_artist_albums.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Albums

    <a data-toggle="collapse" href="#artist_albums_new_form">
      Add album
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @artist.albums.each do |album| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to album, album %>

        <%= link_to album, method: :delete, data: { confirm: "Do you really want to delete this album" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="artist_albums_new_form">
        <%= render partial: "artists/artist_albums_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/artists/_artist_albums_new_form.html.erb
<%= form_with(model: @album, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :album_art %>

    <%= f.text_field :album_art, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :genre_id %>

    <%= f.collection_select :genre_id, Genre.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :artist_id, value: @artist.id %>

  <%= f.submit "Create album", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/artists/_artist_songs.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Songs

    <a data-toggle="collapse" href="#artist_songs_new_form">
      Add song
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @artist.songs.each do |song| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to song, song %>

        <%= link_to song, method: :delete, data: { confirm: "Do you really want to delete this song" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="artist_songs_new_form">
        <%= render partial: "artists/artist_songs_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/artists/_artist_songs_new_form.html.erb
<%= form_with(model: @song, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :album_id %>

    <%= f.collection_select :album_id, Album.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :artist_id, value: @artist.id %>

  <%= f.submit "Create song", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/artists/_artists_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "artists_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :artist_image_cont, "Artist image contains" %>
    <%= f.text_field :artist_image_cont, :class => "form-control", :placeholder => "Artist image contains" %>
  </div>

  <div class="form-group">
    <%= f.label :artist_bio_cont, "Artist bio contains" %>
    <%= f.text_field :artist_bio_cont, :class => "form-control", :placeholder => "Artist bio contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :albums_name_cont, "Albums name contains" %>
    <%= f.text_field :albums_name_cont, :class => "form-control", :placeholder => "Albums name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :songs_name_cont, "Songs name contains" %>
    <%= f.text_field :songs_name_cont, :class => "form-control", :placeholder => "Songs name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/artists" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#artists_filters">
  Show filters
</a>

app/views/artists/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Artist #<%= artist.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Artist image</dt>
      <dd><%= artist.artist_image %></dd>

      <dt>Artist bio</dt>
      <dd><%= artist.artist_bio %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back artist, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_artist_url(artist), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to artist, method: :delete, data: { confirm: "Do you really want to delete this artist?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(artist.updated_at) %> ago
  </div>
</div>

app/views/artists/_form.html.erb
<% was_validated = artist.errors.any? %>

<%= form_with(model: artist, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% artist_image_class = "form-control" %>
    <% artist_image_was_invalid = artist.errors.include?(:artist_image) %>

    <% if was_validated %>
      <% if artist_image_was_invalid %>
        <% artist_image_class << " is-invalid" %>
      <% else %>
        <% artist_image_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :artist_image %>
    <%= f.text_field :artist_image, class: artist_image_class, placeholder: "Enter artist image" %>
    <% if artist_image_was_invalid %>
      <% artist.errors.full_messages_for(:artist_image).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% artist_bio_class = "form-control" %>
    <% artist_bio_was_invalid = artist.errors.include?(:artist_bio) %>

    <% if was_validated %>
      <% if artist_bio_was_invalid %>
        <% artist_bio_class << " is-invalid" %>
      <% else %>
        <% artist_bio_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :artist_bio %>
    <%= f.text_field :artist_bio, class: artist_bio_class, placeholder: "Enter artist bio" %>
    <% if artist_bio_was_invalid %>
      <% artist.errors.full_messages_for(:artist_bio).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/artists/_list_item.html.erb
<%= link_to artist, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= artist %>
    <small class="text-muted">
      <%= time_ago_in_words(artist.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/artists/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Artist #<%= @artist.id %>
      </h2>

      <div class="card-body">
        <%= render "form", artist: @artist %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Artists

      <%= link_to new_artist_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "artists/artists_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Artists

        <%= link_to new_artist_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @artists, partial: "list_item", as: :artist %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @artists, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/artists/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Artist
      </h2>

      <div class="card-body">
        <%= render "form", artist: @artist %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @artist, partial: "card", as: :artist %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "artists/artist_albums" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "artists/artist_songs" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "artists/artist_album_reviews" %>
  </div>
</div>