config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :album_reviews

      resources :song_reviews

      resources :genres

      resources :artists

      resources :albums

      resources :songs

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "songs#index"
  resources :album_reviews
  resources :song_reviews
  resources :genres
  resources :artists
  resources :albums
  resources :songs
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
  # Direct associations

  belongs_to :artist

  belongs_to :album

  has_many   :song_reviews,
             dependent: :destroy

  # Indirect associations

  has_one    :genre,
             through: :album,
             source: :genre

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/songs_controller.rb
class Api::V1::SongsController < Api::V1::GraphitiController
  def index
    songs = SongResource.all(params)
    respond_with(songs)
  end

  def show
    song = SongResource.find(params)
    respond_with(song)
  end

  def create
    song = SongResource.build(params)

    if song.save
      render jsonapi: song, status: :created
    else
      render jsonapi_errors: song
    end
  end

  def update
    song = SongResource.find(params)

    if song.update_attributes
      render jsonapi: song
    else
      render jsonapi_errors: song
    end
  end

  def destroy
    song = SongResource.find(params)

    if song.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: song
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[show edit update destroy]

  def index
    @q = Song.ransack(params[:q])
    @songs = @q.result(distinct: true).includes(:song_reviews, :album,
                                                :artist, :genre).page(params[:page]).per(10)
  end

  def show
    @song_review = SongReview.new
  end

  def new
    @song = Song.new
  end

  def edit; end

  def create
    @song = Song.new(song_params)

    if @song.save
      message = "Song was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @song, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to @song, notice: "Song was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    message = "Song was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to songs_url, notice: message
    end
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:name, :album_id, :artist_id)
  end
end

app/views/songs/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Song #<%= song.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= song.name %></dd>

      <dt>Album</dt>
      <dd>
        <% if @song.album.present? %>
          <%= link_to song.album, song.album %>
        <% end %>
      </dd>

      <dt>Artist</dt>
      <dd>
        <% if @song.artist.present? %>
          <%= link_to song.artist, song.artist %>
        <% end %>
      </dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back song, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_song_url(song), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to song, method: :delete, data: { confirm: "Do you really want to delete this song?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(song.updated_at) %> ago
  </div>
</div>

app/views/songs/_form.html.erb
<% was_validated = song.errors.any? %>

<%= form_with(model: song, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = song.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% song.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% album_class = "form-control" %>
    <% album_was_invalid = song.errors.include?(:album) %>

    <% if was_validated %>
      <% if album_was_invalid %>
        <% album_class << " is-invalid" %>
      <% else %>
        <% album_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :album_id %>
    <%= f.collection_select :album_id, Album.all, :id, :to_s, {}, class: "form-control" %>
    <% if album_was_invalid %>
      <% song.errors.full_messages_for(:album).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% artist_class = "form-control" %>
    <% artist_was_invalid = song.errors.include?(:artist) %>

    <% if was_validated %>
      <% if artist_was_invalid %>
        <% artist_class << " is-invalid" %>
      <% else %>
        <% artist_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :artist_id %>
    <%= f.collection_select :artist_id, Artist.all, :id, :to_s, {}, class: "form-control" %>
    <% if artist_was_invalid %>
      <% song.errors.full_messages_for(:artist).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/songs/_list_item.html.erb
<%= link_to song, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= song %>
    <small class="text-muted">
      <%= time_ago_in_words(song.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/songs/_song_song_reviews.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Song Reviews

    <a data-toggle="collapse" href="#song_song_reviews_new_form">
      Add song review
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @song.song_reviews.each do |song_review| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to song_review, song_review %>

        <% if current_user == song_review.user %>
          <%= link_to song_review, method: :delete do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="song_song_reviews_new_form">
        <%= render partial: "songs/song_song_reviews_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/songs/_song_song_reviews_new_form.html.erb
<%= form_with(model: @song_review, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <%= f.label :body %>

    <%= f.text_field :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title %>

    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :stars %>

    <%= f.text_field :stars, class: "form-control" %>
  </div>

  <%= f.hidden_field :song_id, value: @song.id %>

  <%= f.submit "Create song review", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/songs/_songs_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "songs_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :album_name_cont, "Album name contains" %>
    <%= f.text_field :album_name_cont, :class => "form-control", :placeholder => "Album name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :artist_artist_image_cont, "Artist artist_image contains" %>
    <%= f.text_field :artist_artist_image_cont, :class => "form-control", :placeholder => "Artist artist_image contains" %>
  </div>

  <div class="form-group">
    <%= f.label :genre_name_cont, "Genre name contains" %>
    <%= f.text_field :genre_name_cont, :class => "form-control", :placeholder => "Genre name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/songs" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#songs_filters">
  Show filters
</a>

app/views/songs/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Song #<%= @song.id %>
      </h2>

      <div class="card-body">
        <%= render "form", song: @song %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/songs/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Songs

      <%= link_to new_song_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "songs/songs_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Songs

        <%= link_to new_song_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @songs, partial: "list_item", as: :song %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @songs, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/songs/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Song
      </h2>

      <div class="card-body">
        <%= render "form", song: @song %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/songs/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @song, partial: "card", as: :song %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "songs/song_song_reviews" %>
  </div>
</div>